### ISSUE TITLE
libdsm Licensing terms

### ISSUE THREAD

**Issue by PratikBisht** [videolabs/libdsm#100]
Hi,
Sorry if this is a noob question but I am not smart when it comes to License terms.
I understand that libdsm is available under both GPLv3+Commercial license.
Also it has a dependency on libtasm1 which is only available under GPLv3.
So if I want to use libdsm under commercial license in my iOS/Android app, how am I supposed to use libtasn1 along with that?

**Comment by jbkempf** [comment]
We have a commercial replacement for this.
