### ISSUE TITLE
How to change the 64bit time to 32bit time?

### ISSUE THREAD

**Issue by killpig** [videolabs/libdsm#102]
I use this libdsm for iOS project.

I use the follow funtion to get time of 64 bit.
                  uint64_t     utime=smb_stat_get(st, SMB_STAT_MTIME);

But how to change the 64Bit time to local time on iOS.

                struct tm *localtime(const long * tm32);

How to change the 64bit time to 32bit time? Who can help me ? Thank you.

**Comment by jbkempf** [comment]
struct tm *localtime(const time_t *timep);

Just cast utime into localtime argument.

But this is not the place to ask.

**Comment by killpig** [comment]
How to cast utime into localtime argument?
