### ISSUE TITLE
 How to cast utime into localtime argument?

### ISSUE THREAD

**Issue by killpig** [videolabs/libdsm#103]
I use this libdsm for iOS project.
I use the follow funtion to get time of 64 bit.

uint64_t utime=smb_stat_get(st, SMB_STAT_MTIME);

But how to change the 64Bit time to local time on iOS.

struct tm *localtime(const time_t *timep);

 How to cast utime into localtime argument?

**Comment by jbkempf** [comment]
This is still not the place to ask. This is a bugtracker. 

Ask on a forum ir StackOverflow.
