### ISSUE TITLE
Version: in .pc file is set to Unknow

### ISSUE THREAD

**Issue by marillat** [videolabs/libdsm#107]
BDSM_PACKAGE_VERSION is set by the package_version.sh script who is supposed to return the version if a .version file contains this value. As the .version file is missing then the Version: field in libdsm.pc is set to Unknow.

**Comment by jbkempf** [comment]
True. The only way to do a proper .pc file from source tarball is to use the configure, and not regenerate it from configure.ac. Else, it will fail.

**Comment by marillat** [comment]
Release tarball doesn't have a configure file.

**Comment by jbkempf** [comment]
Yes, it does:
https://github.com/videolabs/libdsm/releases/download/v0.2.7/libdsm-0.2.7.tar.gz

**Comment by marillat** [comment]
We have two source tarballs. I downloaded this one (without the configure file) :

https://github.com/videolabs/libdsm/archive/v0.2.7.tar.gz

**Comment by chouquette** [comment]
That's because the link your provided is a snapshot generated by github, as opposed to the developers provided tarball, generated by `make distcheck`, which contains the configure script.

**Comment by jbkempf** [comment]
Can we remove the github crap?

**Comment by chouquette** [comment]
Not to my knowledge
