### ISSUE TITLE
samba-4.6.5 Can not login with guest account

### ISSUE THREAD

**Issue by Kxuan** [videolabs/libdsm#112]
I am trying to access my local samba share without username and password using libdsm. But it seems that libdsm always trying to send a password hash to server, and I cannot prevent it.

I capture the network data of libdsm and gvfs-samba(libsambaclient), this is the screenshot of auth packet:
![ScreenShot](http://kxuan.tech/wp-content/uploads/2017/07/2017-07-06-10-41-11屏幕截图.png)
It shows that libsambaclient (the right part of the screenshot) set "Lan Manager Reponse" & "NTLM Repnose" to empty value, but liBDSM does not.

Then I enable the DEBUG_PASSWORD for samba, and get these logs:
**samba logs with liBDSM**:
```
[2017/07/06 10:17:37.418482, 100, pid=10135, effective(0, 0), real(0, 0), class=auth] ../source3/auth/auth.c:197(auth_check_ntlm_password)
  user_info has passwords of length 24 and 168
```
**samba logs with gvfs-samba**:
```
[2017/07/06 10:16:21.607910, 100, pid=9646, effective(0, 0), real(0, 0), class=auth] ../source3/auth/auth.c:197(auth_check_ntlm_password)
  user_info has passwords of length 0 and 0
```
The guest auth module in samba server will be skipped if we send a password hash. So we always get an AUTH_FAIL nt_status and do not fallback to guest.

**Please help me, and let me know how to prevent liBSDM send the password hash**

This is a part of my test code:
```C
session = smb_session_new();
if (!session) {
	goto err;
}

if (smb_session_connect(session, "", server_addr.s_addr, SMB_TRANSPORT_NBT) != 0) {
	goto err;
}

// I will get a DSM_ERROR_GENERIC in smb_session_login, if any of these fields set to NULL
smb_session_set_creds(session, "", "", "");

int dsm_err = smb_session_login(session);
if (dsm_err != 0) {
	// dsm_err == DSM_ERROR_NT
	int nt_status = smb_session_get_nt_status(session);
	// nt_status == NT_STATUS_LOGON_FAILURE
	goto err;
}
```

**Comment by jbkempf** [comment]
Thanks for the very detailed analysis. I think I've seen this issue reported already...

**Comment by jbkempf** [comment]
Related to #67 ?

**Comment by Kxuan** [comment]
@jbkempf I am not sure whether it is related to #67.

But I do a quick fix for this issue, I will create a PR soon.
