### ISSUE TITLE
File upload/write to shared folder,but cannot update the file status

### ISSUE THREAD

**Issue by zhuwo** [videolabs/libdsm#116]
Currently, I want to upload file to a shared folder. But after I upload file, I want to read the status of the uploaded file, I find the creation time, the accessTime ... are all **1970**. So I look up interface for writing these status o file when uploading, but I failed.  So can I ask you to provide interface to write these status as it is very important to me? Looking forward to your reply.

**Comment by Kxuan** [comment]
It seems a bug of your samba server... For me, the time is correct.
Also, I think we need a function to implement TRANS2_SET_PATH_INFORMATION (0x0006).

**Comment by Kxuan** [comment]
And your name is very interesting.

**Comment by zhuwo** [comment]
@Kxuan  Thank you for your answer, it Maybe actually a bug of our samba server. But if the library provides the interface, maybe we can overcome with it
By the way, do your name means **Cool**?.

**Comment by jbkempf** [comment]
What is your samba server?

**Comment by jbkempf** [comment]
Cannot reproduce.
