### ISSUE TITLE
how to build the lib for arm?

### ISSUE THREAD

**Issue by lingfuyi** [videolabs/libdsm#119]
when i select the build=arm-arago-linux-gnueabi-gcc host=arm ,is build faild

**Comment by chouquette** [comment]
Please provide the configure command you use, and the build output

**Comment by lingfuyi** [comment]
hello
my enviorment is 
SMB-SERVER: a Anonymous access smb server (arm),have already verify it can access on windows: //10.44.53.100
SMB-CLIENT: cross build libdsm ,build& run in arm board succeed

on condition that  the smb server is only support anonymous access ,so

my app program is :x:  

int main()
{
	struct in_addr addr;  
	smb_session   *session;
	smb_tid     tid;
	smb_fd      fd;
	int ret;
	session = smb_session_new();
	if (session == NULL)
		exit(1);

	printf("smb_session_new ok\n");
	inet_aton("10.44.53.88", &addr);

	if (smb_session_connect(session, "", 
	  addr.s_addr, SMB_TRANSPORT_TCP))
	{
		printf("Unable to connect to host\n");
		exit(2);
	}
	printf("connect to host ok\n");

	smb_session_set_creds(session, "", "login", "");
	printf("start login\n");
	ret = smb_session_login(session);
	if (ret)
	{
		if (session->guest)
			printf("Logged in as GUEST \n");
		else
			printf("Successfully logged in\n");
	}
	else
	{
		printf("Auth failed =%d\n",ret);
		exit(3);
	}

	tid = smb_tree_connect(session, "share" , tid);
	if (!tid)
	{
		printf("Unable to connect to share\n");
		exit(4);
	}

	fd = smb_fopen(session, tid, "\\share" , SMB_MOD_RW , &fd);
	if (!fd)
	{
		printf("Unable to open file\n");
		exit(5);
	}

	char buffer[512];
	smb_fread(session, fd, buffer, 512);

	/* Use data */

	smb_fclose(session, fd);
	smb_tree_disconnect(session, tid);
	smb_session_destroy(session);

	return(0);
	return(0);
}


is always run faild in Auth failed =%d\n", and the ret=0,

**Comment by lingfuyi** [comment]
hello , i succeed run the so in arm board and succeed write&read file ;
i fix the example code as:
#include <stdio.h>  
#include <stdlib.h>  
#include <unistd.h>  
#include <string.h>  
#include <netinet/in.h>  
#include <sys/socket.h>  
#include <sys/types.h>
#include "bdsm/bdsm.h"

#include "../src/smb_types.h"
#include <stdio.h>

int main()
{
	struct in_addr addr;  
	smb_session   *session;
	smb_tid     tid;
	smb_fd      fd;
	int ret , len;
	session = smb_session_new();
	if (session == NULL)
		exit(1);

	printf("smb_session_new ok\n");
	inet_aton("10.44.53.88", &addr);

	if (smb_session_connect(session, "", 
	  addr.s_addr, SMB_TRANSPORT_TCP))
	{
		printf("Unable to connect to host\n");
		exit(2);
	}
	printf("connect to host ok\n");

	smb_session_set_creds(session, "", "login", "");
	printf("start login\n");
	ret = smb_session_login(session);
	if (!ret)
	{
		if (session->guest)
			printf("Logged in as GUEST \n");
		else
			printf("Successfully logged in\n");
	}
	else
	{
		printf("Auth failed =%d\n",ret);
		exit(3);
	}
	printf("start smb_tree_connect\n");

	ret = smb_tree_connect(session, "share" , &tid);
	if (ret)
	{
		printf("Unable to connect to share\n");
		exit(4);
	}
	printf("start smb_fopen\n");
	ret = smb_fopen(session, tid, "hello" , SMB_MOD_RO , &fd);
	if (ret)
	{
		printf("Unable to open file ret =%d fd = %d\n",ret , fd);
		exit(5);
	}
	printf("start smb_fread\n");

	char buffer[512];
	len = smb_fread(session, fd, buffer, 512);
	printf("len =%d buffer=%s\n",len ,buffer);
	/* Use data */

	smb_fclose(session, fd);
	smb_tree_disconnect(session, tid);
	smb_session_destroy(session);

	return(0);
	return(0);
}

please update your example code ,and now ,how to build the code for windows dll

**Comment by jbkempf** [comment]
You need to use the correct triplet, indeed.
