### ISSUE TITLE
libdsm.a  faild to load

### ISSUE THREAD

**Issue by lingfuyi** [videolabs/libdsm#120]
after i build the libdsm is create a libdsm.a libdsm.so ;
when i use cmd  gcc -o main main.c  ./libdsm.so  is succeed to build the program,
but when is use cmd gcc -o main main.c ./libdsm.a have some error to 
undefined refrence to asn1_der_dercoding....more errors

but when i use nm libdsm.a > a.out   ,i find the symbol is in the lib

**Comment by jbkempf** [comment]
You are supposed to use ar to create a .a
