### ISSUE TITLE
support for connection from linux to windows

### ISSUE THREAD

**Issue by ankravch** [videolabs/libdsm#129]
From a linux server I am able to access a shared folder on windows
smbclient -L windows_server -U akravchenko
Enter SAMBA\akravchenko's password:

But I get "Auth failed" from 
  smb_session_set_creds(session, "windows_server", "akravchenko", pswd);
  result = smb_session_login(session);
 in www/source/c/example1.c

Do you support a connection from linux to windows at all ?

**Comment by jbkempf** [comment]
Old question.
