### ISSUE TITLE
I hereby raise an objection to the 'Portable, Theoretically' claim

### ISSUE THREAD

**Issue by Pecacheu** [videolabs/libdsm#136]
Can't build on Windows using CygWin.

I can't figure out how to install the dependencies `libtasn1-3-bin libbsd-dev` and the program won't build without them. It seems like a nice library, but unfortunately it's not very useful if I can't use it cross platform, my program needs to work on Mac, Linux, and Windows, and I don't see why a library that should theoretically only need network access and memory allocation to operate should need any dependency, no reason it shouldn't compile on Windows with a POSIX layer.

**Comment by jbkempf** [comment]
VLC uses dsm on iOS, Android, macOS and related platforms. It even compiles on Linux and BSD.
