### ISSUE TITLE
Do we support ADS (alternate data streams)?

### ISSUE THREAD

**Issue by ncptbtptp** [videolabs/libdsm#148]
Guys, we are looking for a library as SMB client on Linux to read files from a Windows SMB server. Do we support below operation, regarding NTFS ADS (alternate data streams)?

- Query the list of data streams of files on SMB server.
- Download/read a particular data stream of a file.

Thanks,
Eric

**Comment by jbkempf** [comment]
> Guys, we are looking for a library as SMB client on Linux to read files from a Windows SMB server. 

Have you tried libsmbclient on Linux?

**Comment by ncptbtptp** [comment]
> 
> 
> > Guys, we are looking for a library as SMB client on Linux to read files from a Windows SMB server.
> 
> Have you tried libsmbclient on Linux?

libsmbclient is the first to evaluate. But they don't seem to provide any API to read data streams.
http://mrs.suzu841.com/dox/samba_doxygen/group__libsmbclient.html

**Comment by jbkempf** [comment]
True. So, we don't, but maybe we could.

**Comment by ncptbtptp** [comment]
OK. Thanks for confirming.

**Comment by jbkempf** [comment]
If you want, we could, but you need to be more precise.
