### ISSUE TITLE
0.4.0 fail to build

### ISSUE THREAD

**Issue by marillat** [videolabs/libdsm#157]
Debian unstable amd64
The build fail with
````
Configuring Doxyfile using configuration

../meson.build:274:2: ERROR: run_target got unknown keyword arguments "input", "install", "install_dir", "output"
dh_auto_configure: error: cd obj-x86_64-linux-gnu && LC_ALL=C.UTF-8 meson .. --wrap-mode=nodownload --buildtype=plain --prefix=/usr --sysconfdir=/etc --localstatedir=/var --libdir=lib/x86_64-linux-gnu returned exit code 1
make: *** [debian/rules:4: build] Error 25
````

**Comment by jbkempf** [comment]
Hey @marillat, a bit curious I am.

Why would you use dsm on Linux, instead of libsmbclient?

**Comment by marillat** [comment]
VLC was build against dsm. I noticed that now VLC is build with libsmbclient. So I'll switch to libsmbclient too.

**Comment by jbkempf** [comment]
> VLC was build against dsm. I noticed that now VLC is build with libsmbclient. So I'll switch to libsmbclient too.

dsm was mostly done for Android, iOS, macOS, weird Linux distribs and other weird OSes. It should work on all Linux, but libsmbclient is probably more battle-tested there. On Windows, it should not be needed.
