### ISSUE TITLE
0.4.0 fails to configure for tvOS

### ISSUE THREAD

**Issue by fkuehne** [videolabs/libdsm#158]
When compiling for tvOS, the configure step complains about missing libiconv. When compiling libiconv in VLC's contrib system, it is not being used. For iOS, it uses the system's libiconv (like with the previous build system) without any issue.

Meson log attached.

[meson-log.txt](https://github.com/videolabs/libdsm/files/8186962/meson-log.txt)

**Comment by eli-schwartz** [comment]
So your target system has an iconv available via `-liconv` but Meson is not detecting it? Looking at your build log: 

```
ld: -undefined and -bitcode_bundle (Xcode setting ENABLE_BITCODE=YES) cannot be used together
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Library iconv found: NO
```

**Comment by eli-schwartz** [comment]
Side note:

https://github.com/videolabs/libdsm/blob/38e8f2cedd935a6d980f6a3d874535d5f4db6714/meson.build#L157-L168

This logic could be greatly simplified by Meson 0.60.0 which has `dependency('iconv')`

**Comment by ePirat** [comment]
@eli-schwartz Looking at the meson source it seems it adds the allows undefined flag for some reason when doing this check, not sure why though…

**Comment by eli-schwartz** [comment]
It blzames back to https://github.com/mesonbuild/meson/commit/bb5f2ca3da821d7a8e865cd55a8d5d638e0aab22 which seems fairly reasonable...

What's -bitcode_bundle doing here?

**Comment by ePirat** [comment]
Enables bitcode, necessary for tvOS.

**Comment by ePirat** [comment]
I guess this test needs to filter bitcode flags then, to prevent this issue.

**Comment by jbkempf** [comment]
Any solution?

**Comment by ePirat** [comment]
Will investigate a bit more today once @fkuehne tested it is really the bitcode flag, but if it is, likely needs a fix in meson.

**Comment by fkuehne** [comment]
The configure step completes just fine when removing the bitcode flags from the crossfile.meson and compilation succeeds (App Store submission won't). I'm a bit surprised that this is not an issue with other libraries using meson though, which compile with bitcode support just fine such as dav1d.

[meson-log.txt](https://github.com/videolabs/libdsm/files/8197200/meson-log.txt)

**Comment by fkuehne** [comment]
Indeed this problem disappears by using meson's native support for bitcode. The wrapper code in VLC will be adapted accordingly.
