### ISSUE TITLE
Long directory listing

### ISSUE THREAD

**Issue by elthariel** [videolabs/libdsm#26]
Implements the FIND_NEXT2 message and search continuation

**Comment by txia2015** [comment]
iMoreApps, when I tried to apply your patch. I cannot find smb_find2_close_req definition anywhere. Where can I find smb_find2_close_req definition? Thanks.

**Comment by sylverb** [comment]
txia2015, I'll try to have a look at this but the structure of the message can be found in this documentation : https://tools.ietf.org/html/draft-heizer-cifs-v1-spec-00 (look for SMB_COM_FIND_CLOSE2 message)

**Comment by jbkempf** [comment]
@sylverb that'd be nice.

**Comment by sylverb** [comment]
@jbkempf I guess that you can close this one now !

**Comment by jbkempf** [comment]
Cool.
