### ISSUE TITLE
Support building with OpenBSD

### ISSUE THREAD

**Issue by brad0** [videolabs/libdsm#35]
Trying to build libdsm on OpenBSD it is failing at the moment..

> cc -std=gnu99 -DHAVE_CONFIG_H -I. -O0 -g3 -I./contrib -I./include -I./compat -I/usr/local/include -O2 -pipe -Wall -Wsign-compare -Wextra -I/usr/local/include -pthread -MT src/smb_buffer.lo -MD -MP -MF src/.deps/smb_buffer.Tpo -c src/smb_buffer.c -fPIC -DPIC -o src/.libs/smb_buffer.o
src/smb_buffer.c:31:20: error: alloca.h: No such file or directory

**Comment by brad0** [comment]
Removing just the alloca.h header from smb_buffer.c the build continues. The next issue is..

> cc -std=gnu99 -DHAVE_CONFIG_H -I. -O0 -g3 -I./contrib -I./include -I./compat -I/usr/local/include -O2 -pipe -Wall -Wsign-compare -Wextra -I/usr/local/include -pthread -MT src/smb_fd.lo -MD -MP -MF src/.deps/smb_fd.Tpo -c src/smb_fd.c -fPIC -DPIC -o src/.libs/smb_fd.o
> In file included from ./include/bdsm/smb_types.h:39,
>                 from ./include/bdsm/smb_session.h:36,
>                 from src/smb_session.h:34,
>                 from src/smb_fd.h:34,
>                 from src/smb_fd.c:33:
> /usr/include/netinet/ip.h:49: error: expected specifier-qualifier-list before 'u_int'
> /usr/include/netinet/ip.h:167: error: expected specifier-qualifier-list before 'u_int8_t'
> In file included from src/smb_message.h:35,
>                 from src/smb_fd.h:35,
>                 from src/smb_fd.c:33:
> src/smb_types.h:87: warning: 'struct in_addr' declared inside parameter list
> src/smb_types.h:87: warning: its scope is only this definition or declaration, which is probably not what you want

**Comment by jbkempf** [comment]
Can you retry with the trunk?

**Comment by brad0** [comment]
I haven't seen any commits changing anything that would resolve these issues and trying with 0.0.7 I see that nothing has changed.

**Comment by jbkempf** [comment]
Alloca is in stdlib.h in OpenBSD, you should just ifdef it.

As for the /usr/include/netinet/ip.h, I don't see how it's libdsm fault if the header does not compile...

As for the last one, #include <netinet/in.h> should fix it.

**Comment by jbkempf** [comment]
Alloca.h should now work.

**Comment by jbkempf** [comment]
Alloca.h should now work.

**Comment by jbkempf** [comment]
ping.

**Comment by fkuehne** [comment]
Please re-open if compilation still fails on OpenBSD.
