### ISSUE TITLE
Problems when downloading big files

### ISSUE THREAD

**Issue by sylverb** [videolabs/libdsm#40]
I have a problem that happens when downloading files ! I think that the problem is only occurring in rare cases so I'm only able to get it on big files ... I've done several tests on a 9GB file and I've met 2 kinds of problems :
- File downloads fine but data are corrupted at a given point (could be after 1GB or later)
- smb_session_recv_msg exists with 0 in smb_fread function

Does anyone have any idea of what could happen ? I'm running libdsm on MacOS X but it seems to also happen on iOS/tvOS :I've done this test because I'm using libdsm in libvlc for iOS, and for some reason the playback of videos over smb is always crashing after few minutes ...

**Comment by jbkempf** [comment]
Do you have a backtrace of the crash?

**Comment by sylverb** [comment]
On my MacOS it's not crashing ... I've no backtrace for iOS but I can try to get one !

**Comment by sylverb** [comment]
I've done a quick test : downloading the 9GB file from tvOS (AppleTV) is "working" (i.e. not crashing) when using libdsm outside of libvlc ! I guess that libvlc is crashing due to the fact that the read fails ...
I've done one other test : endless find queries on a folder with 2000+ files ! It ends failing after 1289 find sequences for first test and 1258 sequences at 2nd try !
I've checked with Xcode leaks app and it detects no leaks ... I guess that the problem is similar to the one I have with smb_read ! I'll enable debug traces to investigate further ...

**Comment by sylverb** [comment]
Another test that could be interesting to understand what's going on :
if I do a list request, wait 5min and 10 seconds and do another list request (without closing session between both requests), the second request fails !

**Comment by sylverb** [comment]
Ok what I see in wireshark is that the server is sending a NBSS Session keep-alive after 5 minutes ... I guess that this message is not handled and the server is closing the session on his side ...

**Comment by jbkempf** [comment]
So, is it a VLC or a libDSM issue?

**Comment by sylverb** [comment]
It's for sure a problem in libdsm ! I've done all my recent tests just using a libdsm with a modified version of dsm.c test application ! Libdsm stops working if you keep your session open more than 5 minutes (after keep alive delay) ...
Maybe there is also a problem in vlc which is not handling the failure properly and is crashing, but the root cause of the problem is in libdsm !

**Comment by jbkempf** [comment]
OK, thanks for clarifying.

**Comment by sylverb** [comment]
From what I've understood about the way libdsm works, I think it will be hard to solve this issue in a clean way without a major refactoring !
Today, exchanges with the server are based in a query/answer mechanism and queries are always done by the client (libdsm). It makes impossible to handle asynchronous messages coming from the server !
What should be done is a main task that is always waiting for socket messages, and each time it gets a message, it checks what kind of message it has just received and forwards it to the corresponding handle ... It is of course a major refactoring of the library !
Another option is to make a dirty hack in netbios_session_packet_recv function to check if the received message is a keep-alive and if it is one, it answers keep-alive message and waits again for the expected answer ! This hack will only work when the library is waiting for answers all the time, so it should at least workaround the download issue ...
Now this is my understanding of how libdsm is working after few minutes of analysis, so I may be wrong with my understanding ...

**Comment by sylverb** [comment]
I've done some tests with filtering keep alive messages in the receive function with better but not perfect results ! Actually there is a major problem with this receive function : it assumes that every recv call will return at maximum 1 message or a part of a message to reassemble ... But as it returns the content of the socket, we could have anything in it : several keep alive messages, answer to a request followed by a keep alive message, last block of a message to reassemble followed by a keep alive message, etc ...
I've also done an big file download with disabling keep alive message on server side and I still have some corruption, so I guess that we sometimes have problems with reassembling that are not caused by keepalive messages ! I'll try to make a proper receive function and check if corruption is still occurring ...

**Comment by jbkempf** [comment]
Great job!
