### ISSUE TITLE
Review RNG code

### ISSUE THREAD

**Issue by jbkempf** [videolabs/libdsm#51]
Review RNG code

**Comment by elthariel** [comment]
iirc, the initial rand was pretty bad but now we're reading from /dev/urandom ?

**Comment by jbkempf** [comment]
In smb_ntlm_generate_challenge, we just have urandom, and this is clearly not enough for iOS/OSX or other platforms where /dev/urandom is not present.

**Comment by jbkempf** [comment]
Moreover, it's possible we need to start the generator before using it.

**Comment by elthariel** [comment]
This is totally enough for OSX. I don't know about iOS, but it's likely the
same.

For other platforms where /dev/urandom is not present, i agree we'll need
something else. But now i think about it, which platform except windows is
it not available ?

**Comment by jbkempf** [comment]
Linux, Android, BSD and OSX should be OK, indeed.
For iOS, we should use Randomization Services https://developer.apple.com/library/ios/documentation/Security/Reference/RandomizationReference/index.html#//apple_ref/doc/uid/TP40007281
For Windows and WinRT, we need to use the CryptoGen calls (see VLC for this)

**Comment by elthariel** [comment]
Windows and WintRT does not need libdsm anyway.
+1 for ios

**Comment by jbkempf** [comment]
Well, WinRT does actually :)

**Comment by jbkempf** [comment]
It's possible that iOS works with urandom, a contrario from what the code says.

**Comment by jbkempf** [comment]
So, the issue is only remaining for WinRT. Let's close it for now.
