### ISSUE TITLE
No details about failure reasons at interface

### ISSUE THREAD

**Issue by sylverb** [videolabs/libdsm#55]
Most functions are just giving a success/fail status but there is no way to know the reason why it fails.
In my file/folder delete & folder creation functions, I use the returned value to tell the error code but I'm not sure it's the best way to achieve this can't be generalized to all functions ...
I guess that passing an optional "error" pointer in interface functions to return error code would be a better way to do.
Before starting any coding, I just wanted your point of view !

**Comment by jbkempf** [comment]
OK, simple:
* use integers for status, and not unsigned
* use negative values for errors
* use 0 for success

**Comment by sylverb** [comment]
what about keeping -1 for error and using errno ?

**Comment by jbkempf** [comment]
No. errno is a thread-safety mess, if you want to be cross platform.

**Comment by jbkempf** [comment]
See 307759c634b281b187f9f23da44952c5b21b341f to get the base.

**Comment by jbkempf** [comment]
Let's considered that as fixed.
