### ISSUE TITLE
SIGPIPE

### ISSUE THREAD

**Issue by solidusex** [videolabs/libdsm#68]
Why does not disable the socket sigpipe, this will result in many platform process exit.

**Comment by jbkempf** [comment]
Sorry, but are you sure it's the role of the library to do this?

**Comment by solidusex** [comment]
yes, because most applications have third-party libraries start threads , sigpipe make these threads crashed directly. 

Also , why not turn off the old and useless functions? For example, where it will be used? just one line of code logic.

**Comment by jbkempf** [comment]
Sorry, but no. This has to be managed by the application. We cannot know what to do with this.

If some library consumer wants to manage those, how can it do it correctly?
