### ISSUE TITLE
Is there a way to build it for tvos?

### ISSUE THREAD

**Issue by galean** [videolabs/libdsm#69]

**Comment by TimOliver** [comment]
Hi there! I'm maintaining an iOS library for libDSM: https://github.com/TimOliver/TOSMBClient

It SHOULD be compatible with tvOS, but I haven't actually tested it properly yet. Also, at the moment, statically linking it to an app contravenes the LGPL license agreement (I'm working on making it dynamically linked to fix that!) so you'll need to be wary of that if you plan to release an app using it for now.

Hope that helped!

**Comment by jbkempf** [comment]
Be careful, because of bitcode it's very possible that you need a commercial license on AppleTV anyway.
