### ISSUE TITLE
smb_session_is_guest return wrong after logined

### ISSUE THREAD

**Issue by ifreedom** [videolabs/libdsm#72]
After call smb_session_login which return 0, the smb_session_is_guest return -1 as Not Logged.

After view the code, I found the smb_session_login_ntlm function not set session->logged variable when login success.

**Comment by tguillem** [comment]
Thanks for the report.

It's fixed by https://github.com/videolabs/libdsm/commit/c7d478eb5cb6183dd9d854d3ee3f03c8fbc92e6a
