### ISSUE TITLE
License

### ISSUE THREAD

**Issue by naxos** [videolabs/libdsm#81]
Hi, I know it's a bit off-topic, because some of the following is a general licensing issue. Please point me in the right direction, if this is the wrong place for this question.

I have an Objective-C project, which creates a dynamic library that wraps libdsm. To be able to use this library in a commercial setting, I assume that I have the following options

a) Make my project available under the LGPL (sufficient because the library is *dynamic*), or
b) Obtain a proprietary license from VideoLAN

Is that correct?

Now, if I go for option a), but want to make my library available to people who find the LGPL too restrictive, I assume I can put it under dual-license (e.g. MIT/LGPL). If people however, choose to use my library under the MIT License, I also assume that they require a proprietary license from VideoLAN.

Is that also correct?

**Comment by jbkempf** [comment]
This is correct reasoning. If people want something more liberal than the LGPL, they need a commercial license, whether they are a downstream directly or through a different library.

And on iOS and tvOS, this is probably mandatory, because of the linking on those platforms.

**Comment by naxos** [comment]
Sorry, but I do not understand you last point. iOS from version 8 supports dynamic linking.

**Comment by jbkempf** [comment]
Yes, but not if you want iOS7 support. And also, not if you activate bitcode (tvOS) or allow recompilation from Apple.

**Comment by naxos** [comment]
Ok, understood. I can use my dynamic library (which includes libdsm under LGPL) in a commercial iOS app (requiring iOS 8+) as long as I switch off the bitcode option for the app. Since tvOS and watchOS require bitcode, a proprietary license is required for tv/watch apps.

For the moment LGPL sufficient for me. I'll make my library available on GitHub. If at some point I require a proprietary license, I'll send a mail.

Thanks for your support!

**Comment by jbkempf** [comment]
Your dynamic library needs to be open source, though, if it statically links to libdsm. But yes.

**Comment by naxos** [comment]
Yes sure, I'll publish it under the LGPL and possibly a more liberal license, which people can use if they obtain a proprietary license from you.

**Comment by naxos** [comment]
Here we go, dual-licensed under LGPL and MIT license:

https://github.com/naxos/SMBClient

Let me know, if you have any feedback.

**Comment by jbkempf** [comment]
I'd prefer a more explicit explanation about licensing in the README, but that seems fine.

**Comment by naxos** [comment]
Ok, thanks. I referred to COPYING in the README concerning licensing.

**Comment by naxos** [comment]
Allow me two more questions on the license issue:

1. libdsm depends on libtasn1, which is licensed under LGPL (only). Considering this, what sense does your commercial license option make?

2. You said that enabling bitcode for a commercial app, which dynamically links to a library under LGPL would break the LGPL. Do you think this is so a) possibly, b) probably, or c) definitely?

**Comment by jbkempf** [comment]
1. libtasn1 is replaceable for commercial licensees

2. very probably.

**Comment by naxos** [comment]
Thanks. When you have a spare minute, I would be interested in your reasoning concerning point 2.

**Comment by jbkempf** [comment]
bitcode means recompilation and linking to non-open source code

**Comment by naxos** [comment]
Hm, while both the app and the dynamic library might get recompiled by Apple and stripped off unnecessary architectures, doesn't the dynamic library remain to be a dynamically linked library? I can't see where the linking is affected.

**Comment by jbkempf** [comment]
The issue is not linking at all here. It's the fact that you cannot know what code is shipped.

**Comment by naxos** [comment]
I see your point. And I don't want to misuse this place for a general discussion on this issue. Let's leave it like that. Thanks for bearing with me.

**Comment by jbkempf** [comment]
This is a debatable issue, which is why I advise to take a commercial license in those cases.

**Comment by naxos** [comment]
Absolutely. My intention was not to argue that.

**Comment by jbkempf** [comment]
So, to be on the safe side, I advise commercial licenses on those cases (same thing with WinRT btw)
