### ISSUE TITLE
How do I build this for android?

### ISSUE THREAD

**Issue by mutaherraza** [videolabs/libdsm#97]
How to build libdsm for android?

**Comment by mutaherraza** [comment]
I haven't been able to find any buildscript or any help regarding it!

**Comment by jbkempf** [comment]
Sorry, but it's standard autotools.

**Comment by mutaherraza** [comment]
Well just to share for someone else with same query, this helped:

./bootstrap
export CC=
export CFLAGS=
./configure --disable-shared --enable-static --disable-programs --host=arm-linux-androideabi --prefix=$PLATFORM_PREFIX
make
make install
