### ISSUE TITLE
libdsm building ERROR...

### ISSUE THREAD

**Issue by jiapei100** [videolabs/libdsm#99]
Hi, all:

I tried to build the most recent libdsm-git (0.2.7) under Ubuntu 16.04.1. However, I got the following error messages:

```
make[1]: Entering directory '.../libdsm'
  CCLD     dsm
./.libs/libdsm.so: undefined reference to `closesocket'
collect2: error: ld returned 1 exit status
Makefile:738: recipe for target 'dsm' failed
make[1]: *** [dsm] Error 1
make[1]: Leaving directory '.../libdsm'
Makefile:508: recipe for target 'all' failed
make: *** [all] Error 2
```

Any suggestions?

Cheers
Pei

**Comment by jbkempf** [comment]
Are you sure closesocket is not present on Ubuntu?

**Comment by chouquette** [comment]
closesocket is windows specific, if you're not configuring libdsm as *-mingw32, then there's no reason to require it, and as I don't have the issue on debian, I would tend to say there's an issue on your side.

**Comment by jiapei100** [comment]
Even Now, this issue continues...
I'm using Ubuntu 16.04.3

> $ lsb_release -a
> No LSB modules are available.
> Distributor ID: Ubuntu
> Description:    Ubuntu 16.04.3 LTS
> Release:        16.04
> Codename:       xenial

Now, the issues are:

>  Entering directory '/media/jiapei/Data/Downloads/videoprocessing/codecs/libdsm'
>   CCLD     dsm
> ./.libs/libdsm.so: undefined reference to `closesocket'
> collect2: error: ld returned 1 exit status
> Makefile:738: recipe for target 'dsm' failed
> make[1]: *** [dsm] Error 1
> make[1]: Leaving directory '/media/jiapei/Data/Downloads/videoprocessing/codecs/libdsm'
> Makefile:508: recipe for target 'all' failed
> make: *** [all] Error 2
> [1]+  Done                    gedit 01_ConfigureHelp.txt

cheers
Pei

**Comment by Kxuan** [comment]
It can be fixed by move "compat.h" out of #if. 

https://github.com/videolabs/libdsm/pull/113/commits/677a4a79bc5b098ec093a1f06f2ab7f6138367d5#diff-abd578a923e4bb162c68bd80625d3608R51

**Comment by chouquette** [comment]
I reworked compat.h/config.h a little, it should work better
